
name: CI

on:
  push:
    branches: [ main, feature/*, hotfix/* ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.201  
    - name: Install dependencies
      run: dotnet restore src
    - name: Build
      run: dotnet build  src --configuration Release --no-restore
    - name: Test
      run: dotnet test src /p:CollectCoverage=true /p:CoverletOutputFormat=opencover --no-restore --verbosity normal    
    - name: Upload Report
      env:
        CODECOV_TOKEN: "07f03a84-da0d-4a6a-bde6-10e27073442b"
      run: bash <(curl -s https://codecov.io/bash)

